export enum Font {
    SofiaProBlack = "SofiaPro-Black",
    SofiaProBlackItalic = "SofiaPro-BlackItalic",
    SofiaProBold = "SofiaPro-Bold",
    SofiaProBoldItalic = "SofiaPro-BoldItalic",
    SofiaProExtraLight = "SofiaPro-ExtraLight",
    SofiaProExtraLightItalic = "SofiaProExtraLight-Italic",
    SofiaProItalic = "SofiaPro-Italic",
    SofiaProLight = "SofiaPro-Light",
    SofiaProLightItalic = "SofiaPro-LightItalic",
    SofiaProMedium = "SofiaPro-Medium",
    SofiaProMediumItalic = "SofiaPro-MediumItalic",
    SofiaProRegular = "SofiaProRegular",
    SofiaProSemiBold = "SofiaPro-SemiBold",
    SofiaProSemiBoldItalic = "SofiaPro-SemiBoldItalic",
    SofiaProUltraLight = "SofiaPro-UltraLight",
    SofiaProUltraLightItalic = "SofiaPro-UltraLightItalic",
}
